define([], function () {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "PersDataDescription": "Example of controls and groups provided by SPFx",
    "PersData_GrGeneralInfo": "Personal data",
    "PersData_GrMoreInfo": "More information",
    "NameFieldLabel": "Name",
    "SurnameFieldLabel": "Surname",
    "DNIFieldLabel": "DNI",
    "AdultFieldLabel": "Adult",
    "AdultFieldOn": "Yes",
    "AdultFieldOff": "No",
    "GendersFieldLabel": "Gender",
    "AgeFieldLabel": "Age",
    "CountryBirthLabel": "Country of birth",
    "LinkLabel": "Search your profile",
    "CompanyFieldLabel": "Company",
    "AboutMeFieldLabel": "About me",
    "Layout": "Layout",
    "Shape": "Shape",
    "ConditionalFieldDescription": "Example of conditional fields. Do not show field or disable it",
    "ConditionalFieldDescriptionTwo": "Another example of conditionals",
    "CFconversationSource": "Select conversation source",
    "CFsearchCriteria": "Search for a source",
    "CFsearchCriteriaPlaceHolder": "Type to search",
    "CFnumberConversations": "Number of conversations to show",
    "MyButtons": "Button usage examples",
    "Option1": "Option 1",
    "Option2": "Option 2",
    "Option3": "Option 3",
    "HeaderType": "Header type",
    "CollectionDataGroupName": "Header",
    "TitleLabel": "Header",
    "Enabled": "Active",
    "EnabledOnText": "Yes",
    "EnabledOffText": "No",
    "SubTitleLabel": "Subtitle",
    "DescriptionCustomLabel": "Custom description",
    "LaboralDataDescription": "More examples of controls and groups provided by SPFx",
    "LaboralData_GrGeneralInfo": "labor information",
    "LaboralData_GrMoreInfo": "Another information",
    "Spain": "Spain",
    "France": "France",
    "EEUU": "EEUU",
    "Germany": "Germany",
    "Male": "Male",
    "Female": "Female",
    "ChangeMe": "Change me",
    "BtnNormalButton": "Normal button",
    "BtnPrimaryButton": "Primary button",
    "BtnHeroButton": "Hero button ('Add' icon)",
    "BtnCommandButton": "Command button",
    "BtnCompoundButton": "Compound button",
    "BtnCompoundButtonDescripcion": 'With some descriptive text',
    "BtnIconButton": "Icon button ('AddFriend' icon)",
    "ErrorValidationString": "Value must be more than 3 characters!",
  }
});