define([], function () {
  return {
    "PropertyPaneDescription": "Descripción",
    "BasicGroupName": "Nombre del grupo",
    "DescriptionFieldLabel": "Campo descripción",
    "PersDataDescription": "Ejemplo de controles y grupos que proporciona SPFx",
    "PersData_GrGeneralInfo": "Datos personales",
    "PersData_GrMoreInfo": "Más información",
    "NameFieldLabel": "Nombre",
    "SurnameFieldLabel": "Apellidos",
    "DNIFieldLabel": "DNI",
    "AdultFieldLabel": "Mayor de edad",
    "AdultFieldOn": "Sí",
    "AdultFieldOff": "No",
    "GendersFieldLabel": "Sexo",
    "AgeFieldLabel": "Edad",
    "CountryBirthLabel": "País de nacimiento",
    "LinkLabel": "Busca en tu perfil",
    "CompanyFieldLabel": "Empresa",
    "AboutMeFieldLabel": "Sobre mi",
    "Layout": "Disposición",
    "Shape": "Forma",
    "ConditionalFieldDescription": "Ejemplo de campos condicionales. No mostrar campo o desahabilitarlo",
    "ConditionalFieldDescriptionTwo": "Otro ejemplo de condicionales",
    "CFconversationSource": "Origen de la conversación",
    "CFsearchCriteria": "Búsqueda de un origen",
    "CFsearchCriteriaPlaceHolder": "Escribe la búsqueda",
    "CFnumberConversations": "Número de conversaciones a mostrar",
    "MyButtons": "Ejemplos de uso de botones",
    "Option1": "Opcion 1",
    "Option2": "Opcion 2",
    "Option3": "Opcion 3",
    "HeaderType": "Tipo de cabecera",
    "CollectionDataGroupName": "Cabecera",
    "TitleLabel": "Titulo",
    "Enabled": "Activo",
    "EnabledOnText": "Sí",
    "EnabledOffText": "No",
    "SubTitleLabel": "Subtítulo",
    "DescriptionCustomLabel": "Descripción personalizada",
    "LaboralDataDescription": "Más ejemplos de controles y grupos que proporciona SPFx",
    "LaboralData_GrGeneralInfo": "Información laboral",
    "LaboralData_GrMoreInfo": "Otra información",
    "Spain": "España",
    "France": "Francia",
    "EEUU": "EEUU",
    "Germany": "Alemania",
    "Male": "Hombre",
    "Female": "Mujer",
    "ChangeMe": "Actualizame",
    "BtnNormalButton": "Botón normal",
    "BtnPrimaryButton": "Botón primario",
    "BtnHeroButton": "Hero button ('Añadir' icono)",
    "BtnCommandButton": "Botón command",
    "BtnCompoundButton": "Botón compound",
    "BtnCompoundButtonDescripcion": "Con algo de texto descriptivo",
    "BtnIconButton": "Botón icono ('AddFriend' icono)",
    "ErrorValidationString": "El valor debe de tener al menos 3 caracteres"
  }
});