declare interface IPersonalPropertyPaneWebPartStrings {
  // PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  PersDataDescription: string;
  PersData_GrGeneralInfo: string;
  PersData_GrMoreInfo: string;
  NameFieldLabel: string;
  SurnameFieldLabel: string;
  DNIFieldLabel: string;
  AdultFieldLabel: string;
  AdultFieldOn: string;
  AdultFieldOff: string
  GendersFieldLabel: string;
  AgeFieldLabel: string;
  AgeMinValue: number;
  AgeMaxValue: number;
  CountryBirthLabel: string;
  LinkLabel: string;
  LaboralDataDescription: string;
  LaboralData_GrGeneralInfo: string;
  LaboralData_GrMoreInfo: string;
  Spain: string;
  France: string;
  EEUU: string;
  Germany: string;
  Male: string;
  Female: string;
  CompanyFieldLabel: string;
  AboutMeFieldLabel: string;
  Layout: string;
  Shape: string;
  ConditionalFieldDescription: string;
  ConditionalFieldDescriptionTwo: string;
  CFconversationSource: string;
  CFsearchCriteria: string;
  CFsearchCriteriaPlaceHolder: string;
  CFnumberConversations: string;
  MyButtons: string;
  Option1: string;
  Option2: string;
  Option3: string;
  HeaderType: string;
  CollectionDataGroupName: string;
  TitleLabel: string;
  Enabled: string;
  EnabledOnText: string;
  EnabledOffText: string;
  SubTitleLabel: string;
  DescriptionCustomLabel: string;
  ChangeMe: string;
  BtnNormalButton: string;
  BtnPrimaryButton: string;
  BtnHeroButton: string;
  BtnCommandButton: string;
  BtnCompoundButton: string;
  BtnCompoundButtonDescripcion: string;
  BtnIconButton: string;
  label: strings;
  ErrorValidationString: string;
  PnPPropertyControlsDescription: string;
  HtmlCodeLabel: string;
  CollectionDataLabel: string;
  ColorLabel: string;
  DateTimeLabel: string;
  MultiSelectLabel: string;
}

declare module 'PersonalPropertyPaneWebPartStrings' {
  const strings: IPersonalPropertyPaneWebPartStrings;
  export = strings;
}
